import type { ModelId } from '../model-catalog.js';
import type { PromptCatalog, PromptEntrypoint, PromptFragment } from './types.js';
import { resolvePromptPath } from './loader.js';

export const SOURCE_CITATION_PROMPT_GUARDRAILS = [
  '=== SOURCE CITATION SAFETY ===',
  'Treat usedSources and sourceCitationSummary as system-captured source seeds from authorized scope setup, not sentence-level semantic citations generated by the model.',
  'Do not invent citations or claim a source was used unless it is present in the system-provided usedSources/sourceCitationSummary.',
  'Do not output server paths, workspace paths, source paths, internal manifest paths, local drive paths, UNC paths, or deployment directories.',
  'Never reveal API keys, JWTs, cookies, passwords, access tokens, refresh tokens, or authorization headers.',
  'Keep the answer body useful; separate source-backed facts from model synthesis, selection advice, and risk notes when relevant.'
].join('\n');

/**
 * Parameters for composing system prompt
 */
export interface ComposeSystemPromptParams {
  global?: string;
  role?: string;
  chip?: string;
  roleName?: string;
  chipName?: string;
}

export interface SelectPromptFragmentsParams {
  fragments: readonly PromptFragment[];
  entrypoint: PromptEntrypoint;
  model: ModelId;
  language: string;
  role: string;
  resourceScope?: string;
  chipId?: string;
  userLevel?: string;
}

export interface ComposeGovernedPromptParams extends SelectPromptFragmentsParams {
  basePrompt?: string;
}

/**
 * Compose a three-layer system prompt from global, role, and chip prompts.
 * Uses === LAYER === separators per D-05.
 *
 * @param params - Object containing optional global, role, chip content and their names
 * @returns Composed system prompt string with layer separators
 */
export function composeSystemPrompt(params: ComposeSystemPromptParams): string {
  const layers: string[] = [];

  if (params.global?.trim()) {
    layers.push(`=== GLOBAL ===\n${params.global.trim()}`);
  }

  if (params.role?.trim() && params.roleName) {
    layers.push(`=== ${params.roleName.toUpperCase()} ===\n${params.role.trim()}`);
  }

  if (params.chip?.trim() && params.chipName) {
    layers.push(`=== ${params.chipName} ===\n${params.chip.trim()}`);
  }

  return layers.join('\n\n');
}

function matchesScope(scope: readonly string[], value: string | undefined): boolean {
  if (scope.includes('*')) {
    return true;
  }
  if (!value) {
    return false;
  }
  return scope.includes(value);
}

/**
 * Select enabled governed prompt fragments for the current request context.
 * Fragments with injectionPolicy "never" are governance-disabled at selection
 * time, so callers cannot accidentally compose them into a system prompt.
 */
export function selectPromptFragments(params: SelectPromptFragmentsParams): PromptFragment[] {
  return params.fragments
    .filter((fragment) => fragment.enabled)
    .filter((fragment) => fragment.injectionPolicy !== 'never')
    .filter((fragment) => fragment.entrypoints.includes(params.entrypoint))
    .filter((fragment) => matchesScope(fragment.models, params.model))
    .filter((fragment) => matchesScope(fragment.languages, params.language))
    .filter((fragment) => matchesScope(fragment.roles, params.role))
    .filter((fragment) => matchesScope(fragment.resourceScopes, params.resourceScope))
    .filter((fragment) => matchesScope(fragment.chipIds, params.chipId))
    .filter((fragment) => matchesScope(fragment.userLevels, params.userLevel))
    .sort((left, right) => right.priority - left.priority || left.id.localeCompare(right.id));
}

/**
 * Compose a governed prompt from selected fragments while keeping the legacy
 * three-layer composer available for existing callers.
 */
export function composeGovernedPrompt(params: ComposeGovernedPromptParams): string {
  const layers: string[] = [];

  if (params.basePrompt?.trim()) {
    layers.push(params.basePrompt.trim());
  }

  layers.push(
    ...selectPromptFragments(params)
      .map((fragment) => fragment.content.trim())
      .filter(Boolean)
  );

  return layers.join('\n\n');
}

export function appendSourceCitationPromptGuardrails(systemPrompt: string | undefined): string {
  const base = systemPrompt?.trim();
  if (base?.includes('=== SOURCE CITATION SAFETY ===')) {
    return base;
  }
  return [base, SOURCE_CITATION_PROMPT_GUARDRAILS].filter(Boolean).join('\n\n');
}

/**
 * Get the full path to a prompt file based on catalog configuration.
 *
 * @param catalog - Prompt catalog with baseDir and file paths
 * @param type - Type of prompt: 'global', 'role', or 'chip'
 * @param name - Name for role or chip prompt (required for role/chip types)
 * @returns Resolved absolute path to the prompt file
 * @throws Error if name is missing for role/chip types
 */
export function getPromptFilePath(
  catalog: PromptCatalog,
  type: 'global' | 'role' | 'chip',
  name?: string
): string {
  const { baseDir, files } = catalog;

  switch (type) {
    case 'global':
      return resolvePromptPath(baseDir, files.global);
    case 'role':
      if (!name) throw new Error('Role name required for role prompt');
      return resolvePromptPath(baseDir, `${files.roles}/${name}.md`);
    case 'chip':
      if (!name) throw new Error('Chip name required for chip prompt');
      return resolvePromptPath(baseDir, `${files.chips}/${name}.md`);
  }
}
